AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Uploader Node.js Project

Resources:
  # API Gateway cu CORS activat
  UploadApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigins: "'*'"
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        MaxAge: 86400

  # Lambda pentru upload
  UploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          BUCKET_NAME: img-upload-v1-adi-2025-12345  # nume global unic
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Events:
        UploadAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            RestApiId:
              Ref: UploadApi  # leagă Lambda de API cu CORS

Outputs:
  UploadAPIEndpoint:
    Description: "API Gateway endpoint pentru upload"
    Value:
      Fn::Sub: "https://${UploadApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload"
