AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Uploader Node.js Project

Resources:
  UploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler       # dacă app.js este în rădăcina proiectului
      Runtime: nodejs18.x
      Environment:
        Variables:
          BUCKET_NAME: img-upload-v1  # nume global unic
      Policies:
        - S3FullAccess
      Events:
        UploadAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: post   # pentru upload fișiere

Outputs:
  UploadAPIEndpoint:
    Description: "API Gateway endpoint pentru upload"
    Value:
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload"
