AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Uploader Node.js Project

Resources:
  UploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler       # dacă app.js este în rădăcina proiectului
      Runtime: nodejs18.x
      Environment:
        Variables:
          BUCKET_NAME: img-upload-v1-adi-2025-12345  # nume global unic
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Events:
        UploadAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: post   # pentru upload fișiere
            Cors:
              AllowOrigins: "'*'"                # permite toate origin-urile
              AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              AllowMethods: "'POST,OPTIONS'"     # metode permise
              MaxAge: 86400                       # cache preflight request

Outputs:
  UploadAPIEndpoint:
    Description: "API Gateway endpoint pentru upload"
    Value:
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload"
