Resources:
  # API Gateway cu CORS activat
  UploadApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Lambda pentru upload
  UploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          BUCKET_NAME: img-upload-v1-adi-2025-12345
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Events:
        UploadAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            RestApiId: 
              Ref: UploadApi

Outputs:
  UploadAPIEndpoint:
    Description: "API Gateway endpoint pentru upload"
    Value:
      Fn::Sub: "https://${UploadApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload"
